# Generated by Django 5.0.1 on 2024-04-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fistName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Terceiro Nome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='segundName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nome'),
        ),
    ]
