# Generated by Django 5.0.1 on 2024-04-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_fistname_alter_profile_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fistName',
            new_name='firstName',
        ),
    ]
