# Generated by Django 5.0.1 on 2024-04-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolfinance', '0002_ativo_data_passivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Ativo'),
        ),
        migrations.AlterField(
            model_name='passivo',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do passivo'),
        ),
    ]
